sudo: required

language: python

services:
  - docker

before_install:
  - docker version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version

install:
  - pip install -r requirements.txt

script:
  - py.test -v test_*.py

after_success:
  - docker build -f Dockerfile -t "$DOCKER_USERNAME"/alpine:3.6 --build-arg TAG=3.6 .
  - docker build -f Dockerfile -t "$DOCKER_USERNAME"/alpine:3.7 --build-arg TAG=3.7 .
  - docker build -f Dockerfile -t "$DOCKER_USERNAME"/alpine:3.8 --build-arg TAG=3.8 .
  - docker build -f Dockerfile -t "$DOCKER_USERNAME"/alpine:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "$DOCKER_USERNAME"/alpine:3.6
  - docker push "$DOCKER_USERNAME"/alpine:3.7
  - docker push "$DOCKER_USERNAME"/alpine:3.8
  - docker push "$DOCKER_USERNAME"/alpine:latest
  - docker logout
