---
name: lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint on GitHub workflows
        run: yamllint .github/workflows
